{
  "name": "autosaaz-server",
  "type": "web",
  "env": "node",
  "buildCommand": "npm install && npm run build",
  "startCommand": "npm start",
  "healthCheckPath": "/health",
  "envVars": [
    {
      "key": "NODE_ENV",
      "value": "production"
    },
    {
      "key": "PORT",
      "generateValue": true
    }
  ]
}
